### ISSUE TITLE
ldap.tls.CAcertificateFilename not encoded as a string

### ISSUE THREAD

**Issue by eclipsetalk** [bitnami/bitnami-docker-airflow#111]
Hello,
I'm trying to use LDAP with Ariflow 2.1.14.
I've noticed 2 issues when one defines ldap.tls certificate:

1. **allowSelfSigned** is not encoded as a string so one needs to use single/double quotes
2.  **CAcertifacteFilename** is not encoded as a string and therefore the web container fails as described below:

```
- File "/opt/bitnami/airflow/webserver_config.py", line 138
    AUTH_LDAP_TLS_CACERTFILE = /opt/bitnami/airflow/certs/"XXXX_corp_ca_2020.pem"
```

The corresponding helm chart:
```
tls:
    enabled: true
    allowSelfSigned: '"False"'
    CAcertificateSecret: "trusted-certs"
    CAcertificateFilename: '"XXXX_corp_ca_2020.pem"'
```

For 1. A quick fix is to add " | quote " in line 132 of file depoyment.yaml
```
            - name: AIRFLOW_LDAP_ALLOW_SELF_SIGNED
              value: {{ .Values.ldap.tls.allowSelfSigned | quote }}
```

Thank you in advance for providing a patch/solution for the CAcertificateFilename.

Eric
