### ISSUE TITLE
Cannot restore persisted state

### ISSUE THREAD

**Issue by buffaloDeveloper** [bitnami/bitnami-docker-airflow#119]
When I stop docker compose and try to restart it throws an error:

```
postgresql_1         | 2021-11-15 22:18:09.395 GMT [95] LOG:  incomplete startup packet
airflow-worker_1     | airflow-worker 22:18:09.39 INFO  ==> Restoring persisted Airflow installation
airflow-worker_1     | airflow-worker 22:18:09.42 INFO  ==> Waiting for Airflow Webserser to be up
airflow_1            | airflow 22:18:10.29 INFO  ==> Configuring Airflow webserver authentication
airflow_1            | airflow 22:18:10.31 INFO  ==> Configuring Airflow database
airflow_1            | airflow 22:18:10.34 INFO  ==> Configuring Celery Executor
airflow_1            | airflow 22:18:10.37 INFO  ==> Waiting for PostgreSQL to be available at postgresql:5432...
postgresql_1         | 2021-11-15 22:18:10.384 GMT [96] LOG:  incomplete startup packet
airflow_1            | airflow 22:18:10.38 INFO  ==> Restoring persisted Airflow installation
airflow_1 exited with code 1
airflow-scheduler_1  | timeout reached before the port went into state "inuse"
airflow-worker_1     | timeout reached before the port went into state "inuse"
airflow-scheduler_1  | cannot resolve host "airflow": lookup airflow on 127.0.0.11:53: no such host
```

I end up having to delete everything to get it working again:

`docker-compose down --volumes --remove-orphans`

Why is this happening?
Docker version 20.10.7, build f0df350
docker-compose version 1.29.2, build 5becea4c
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

Here is my compose file:

```
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  redis:
    image: docker.io/bitnami/redis:6.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_VAR_KAFKA_SERVER=${KAFKA_SERVER}
      - AIRFLOW_VAR_YOUTUBE_API=${YOUTUBE_API}
    volumes:
      - airflow_scheduler_data:/bitnami
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./requirements.txt:/bitnami/python/requirements.txt
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_VAR_KAFKA_SERVER=${KAFKA_SERVER}
      - AIRFLOW_VAR_YOUTUBE_API=${YOUTUBE_API}
    volumes:
      - airflow_worker_data:/bitnami
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./requirements.txt:/bitnami/python/requirements.txt
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_VAR_KAFKA_SERVER=${KAFKA_SERVER}
      - AIRFLOW_VAR_YOUTUBE_API=${YOUTUBE_API}
    ports:
      - '8050:8080'
    volumes:
      - airflow_data:/bitnami
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./requirements.txt:/bitnami/python/requirements.txt
volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    external: true
    name: ti-network

```

Requirements.txt:

```
kafka-python==2.0.2
python-youtube==0.8.1

```
