### ISSUE TITLE
ElacticSearch write_stdout

### ISSUE THREAD

**Issue by eclipsetalk** [bitnami/bitnami-docker-airflow#122]
Hello,
I'm using airflow tag: 2.2.2-debian-10-r7 - I need to setup elasticsearch writ_stdout to true. When I set it in the chart as follow it has no effect:

```
elasticsearch:
  write_stdout: true
  json_format: true
  log_id_template: "{dag_id}_{task_id}_{execution_date}_{try_number}"
  json_fields: asctime, filename, lineno, levelname, message
```

I edited the airflow.cfg to set the values, stopped and restarted airflow. The settings were updated but then there reverted to defaults once the server restarted.
Can I use an env variables to set the write_stdout, and why isn't it working when set in the value.yaml file?

Thanks!
