### ISSUE TITLE
Ariflow 2.2.1

### ISSUE THREAD

**Issue by eclipsetalk** [bitnami/bitnami-docker-airflow#124]
Hello,
I'm using Airflow 2.2.2 (2.2.2-debian-10-r7). Sometimes I can't access the DAGs logs due to a 403 error although I have defined AIRFLOW__WEBSERVER__SECRET_KEY under the web, the scheduler and the worker sections in the helm chart as follow :

```
*** Log file does not exist: /opt/bitnami/airflow/logs/hhd-hoj-form/hoj_comparison/2021-12-03T21:57:51.573290+00:00/1.log
*** Fetching from: http://airflow2prod-worker-0.airflow2prod-worker-headless.airflow-2-prod.svc.cluster.local:8793/log/hxxxxxx/xxxxxx/2021-12-03T21:57:51.573290+00:00/1.log
*** !!!! Please make sure that all your Airflow components (e.g. schedulers, webservers and workers) have the same 'secret_key' configured in 'webserver' section !!!!!
****** See more at https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#secret-key
****** Failed to fetch log file from worker. Client error '403 FORBIDDEN' for url 'http://airflow2prod-worker-0.airflow2prod-worker-headless.airflow-2-prod.svc.cluster.local:8793/log/xxxxxxx/xxxxxxxx/2021-12-03T21:57:51.573290+00:00/1.log'
For more information check: https://httpstatuses.com/403
```

```
- name: AIRFLOW__WEBSERVER__SECRET_KEY_CMD
      valueFrom:
        secretKeyRef:
          name: airflow2-secrets
          key: web-secret-key
    - name: AIRFLOW__WEBSERVER__SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: airflow2-secrets
          key: web-secret-key
    - name: AIRFLOW__WEBSERVER__SECRET_KEY_SECRET
      valueFrom:
        secretKeyRef:
          name: airflow2-secrets
          key: web-secret-key
```
Any pointers are greatly appreciated!
Thanks
