### ISSUE TITLE
Docker install python packages but it doesn't recognize it using the terminal

### ISSUE THREAD

**Issue by guilhermenoronha** [bitnami/bitnami-docker-airflow#133]
### Name and Version

docker.io/bitnami/airflow:2

### What steps will reproduce the bug?

1. docker-compose up the following customized docker-compose file:
version: '2'

```
services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./requirements/requirements.txt:/bitnami/python/requirements.txt
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./requirements/requirements.txt:/bitnami/python/requirements.txt
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - '8080:8080'
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./requirements/requirements.txt:/bitnami/python/requirements.txt
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodata:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
```
The compose file above has mongo containers and also a mounted volume for dags and requirements.txt file. Following is my requirements.txt file:

```
dnspython==1.16.0
pymongo==3.12.0
python-decouple==3.4
python-dotenv==0.19.0
bi-lstm-crf==0.2.1
scikit-learn==0.24.2
```
The compose is mounted successfully as you can see in the log below:
```

airflow-scheduler_1  | Successfully installed bi-lstm-crf-0.2.1 dnspython-1.16.0 joblib-1.1.0 pymongo-3.12.0 python-decouple-3.4 python-dotenv-0.19.0 scikit-learn-0.24.2 scipy-1.8.0 threadpoolctl-3.1.0 torch-1.11.0
...
airflow-worker_1     | Successfully installed bi-lstm-crf-0.2.1 dnspython-1.16.0 joblib-1.1.0 pymongo-3.12.0 python-decouple-3.4 python-dotenv-0.19.0 scikit-learn-0.24.2 scipy-1.8.0 threadpoolctl-3.1.0 torch-1.11.0
...
airflow_1            | Successfully installed bi-lstm-crf-0.2.1 dnspython-1.16.0 joblib-1.1.0 pymongo-3.12.0 python-decouple-3.4 python-dotenv-0.19.0 scikit-learn-0.24.2 scipy-1.8.0 threadpoolctl-3.1.0 torch-1.11.0
```
All the tasks work fine as well, but one: a bash_operator calling a specific python module.

```
container_path = '/opt/bitnami/airflow/dags/'
t10 = BashOperator(
        task_id = 'Run_BILSTM_Learner',
        bash_command = f'python -m bi_lstm_crf "{container_path}test_train_data" --model_dir "{container_path}cartas_anon_model" --num_epoch 500 --save_best_val_model'
        )
```
When I access this specific task log I see the following message:

```
[2022-04-01, 14:30:09 UTC] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python -m bi_lstm_crf "/opt/bitnami/airflow/dags/test_train_data" --model_dir "/opt/bitnami/airflow/dags/cartas_anon_model" --num_epoch 500 --save_best_val_model']
[2022-04-01, 14:30:09 UTC] {subprocess.py:85} INFO - Output:
[2022-04-01, 14:30:09 UTC] {subprocess.py:89} INFO - /opt/bitnami/python/bin/python: No module named bi_lstm_crf
[2022-04-01, 14:30:09 UTC] {subprocess.py:93} INFO - Command exited with return code 1
```
I did some tests. 

1. I accessed the containers file system using docker exec -it container_id /bin/bash
2. Opened python terminal
3. Tried to import any python packages my compose installed such as:
    - from bi_lstm_crf.app import WordsTagger
    - from sklearn.metrics import f1_score, confusion_matrix
4. None worked.

The airflow somehow recognizes all the packages the compose installed and the tasks are executed successfully with the exception of the bashoperator. When I try to use both BashOperator and the terminal itself, I get the mentioned errors.

### What is the expected behavior?

Container terminal recognizes my python packages.

### What do you see instead?

Errors when trying to use bashoperator or the terminal itself.
