### ISSUE TITLE
error: cannot use sqlite with the CeleryExecutor

### ISSUE THREAD

**Issue by buffaloDeveloper** [bitnami/bitnami-docker-airflow#135]
### Name and Version

docker.io/bitnami/airflow-scheduler:2

### What steps will reproduce the bug?

Running on Debian using docker-compose.

```yaml
version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./requirements.txt:/bitnami/python/requirements.txt
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./requirements.txt:/bitnami/python/requirements.txt
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DATABASE_NAME}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
    ports:
      - '8050:8080'
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ./requirements.txt:/bitnami/python/requirements.txt
volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    external: true
    name: ti-network
```

### What is the expected behavior?

The scheduler should be operational.

### What do you see instead?

The scheduler does not appear to be running.

The DAGs list may not update, and new tasks will not be scheduled.

### Additional information
```
airflow-worker_1     | airflow-worker 15:08:04.04 INFO  ==> Configuring Celery Executor
airflow-worker_1     | airflow-worker 15:08:04.16 INFO  ==> Trying to connect to the database server
airflow-scheduler_1  | Traceback (most recent call last):
airflow-scheduler_1  |   File "/opt/bitnami/airflow/venv/bin/airflow", line 5, in <module>
airflow-scheduler_1  |     from airflow.__main__ import main
airflow-scheduler_1  |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/__init__.py", line 35, in <module>
airflow-scheduler_1  |     from airflow import settings
airflow-scheduler_1  |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/settings.py", line 35, in <module>
airflow-scheduler_1  |     from airflow.configuration import AIRFLOW_HOME, WEBSERVER_CONFIG, conf  # NOQA F401
airflow-scheduler_1  |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py", line 1345, in <module>
airflow-scheduler_1  |     conf.validate()
airflow-scheduler_1  |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py", line 293, in validate
airflow-scheduler_1  |     self._validate_config_dependencies()
airflow-scheduler_1  |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py", line 387, in _validate_config_dependencies
airflow-scheduler_1  |     raise AirflowConfigException(f"error: cannot use sqlite with the {self.get('core', 'executor')}")
airflow-scheduler_1  | airflow.exceptions.AirflowConfigException: error: cannot use sqlite with the CeleryExecutor
airflow-worker_1     | Traceback (most recent call last):
airflow-worker_1     |   File "/opt/bitnami/airflow/venv/bin/airflow", line 5, in <module>
airflow-worker_1     |     from airflow.__main__ import main
airflow-worker_1     |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/__init__.py", line 35, in <module>
airflow-worker_1     |     from airflow import settings
airflow-worker_1     |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/settings.py", line 35, in <module>
airflow-worker_1     |     from airflow.configuration import AIRFLOW_HOME, WEBSERVER_CONFIG, conf  # NOQA F401
airflow-worker_1     |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py", line 1345, in <module>
airflow-worker_1     |     conf.validate()
airflow-worker_1     |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py", line 293, in validate
airflow-worker_1     |     self._validate_config_dependencies()
airflow-worker_1     |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/configuration.py", line 387, in _validate_config_dependencies
airflow-worker_1     |     raise AirflowConfigException(f"error: cannot use sqlite with the {self.get('core', 'executor')}")
airflow-worker_1     | airflow.exceptions.AirflowConfigException: error: cannot use sqlite with the CeleryExecutor
```
