### ISSUE TITLE
Worker & Scheduler do not connect to the database on latest images

### ISSUE THREAD

**Issue by dtomlinson91** [bitnami/bitnami-docker-airflow#136]
### Name and Version

bitnami/airflow:2

### What steps will reproduce the bug?

This docker-compose file:

```yaml
version: '3'

services:
  postgresql:
    image: bitnami/postgresql:10
    container_name: airflow_postgressql
    volumes:
      - '/mnt/user/appdata/airflow2/data/postgresql_data:/bitnami/postgresql'
    environment:
      POSTGRESQL_DATABASE: bitnami_airflow
      POSTGRESQL_USERNAME: bn_airflow
      POSTGRESQL_PASSWORD: **masked**
      ALLOW_EMPTY_PASSWORD: "no"
  redis:
    image: bitnami/redis:6.0
    container_name: airflow_redis
    volumes:
      - '/mnt/user/appdata/airflow2/data/redis_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: bitnami/airflow-scheduler:2
    container_name: airflow_scheduler
    environment:
      AIRFLOW_DATABASE_HOST: postgresql
      AIRFLOW_DATABASE_PORT_NUMBER: 5432
      AIRFLOW_DATABASE_NAME: bitnami_airflow
      AIRFLOW_DATABASE_USERNAME: bn_airflow
      AIRFLOW_DATABASE_PASSWORD: **masked**
      AIRFLOW_EXECUTOR: CeleryExecutor
      AIRFLOW_WEBSERVER_HOST: airflow
      AIRFLOW_LOAD_EXAMPLES: "no"
      AIRFLOW_BASE_URL: https://airflow.**masked**.co.uk
      AIRFLOW__WEBSERVER__BASE_URL: https://airflow.**masked**.co.uk
      AIRFLOW_SECRET_KEY: **masked**
      debug: "true"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/mnt/user/appdata/airflow2/dags:/opt/bitnami/airflow/dags'
      - '/mnt/user/appdata/airflow2/requirements.txt"/bitnami/python/requirements.txt'
      - '/mnt/user/appdata/airflow2/data/logs:/opt/bitnami/airflow/logs'
  airflow-worker:
    image: bitnami/airflow-worker:2
    container_name: airflow_worker
    environment:
      AIRFLOW_DATABASE_HOST: postgresql
      AIRFLOW_DATABASE_PORT_NUMBER: 5432
      AIRFLOW_DATABASE_NAME: bitnami_airflow
      AIRFLOW_DATABASE_USERNAME: bn_airflow
      AIRFLOW_DATABASE_PASSWORD: **masked**
      AIRFLOW_EXECUTOR: CeleryExecutor
      AIRFLOW_WEBSERVER_HOST: airflow
      AIRFLOW_LOAD_EXAMPLES: "no"
      AIRFLOW_BASE_URL: https://airflow.**masked**.co.uk
      AIRFLOW__WEBSERVER__BASE_URL: https://airflow.**masked**.co.uk
      AIRFLOW_SECRET_KEY: **masked**
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/mnt/user/appdata/airflow2/dags:/opt/bitnami/airflow/dags'
      - '/mnt/user/appdata/airflow2/requirements.txt"/bitnami/python/requirements.txt'
      - '/mnt/user/appdata/airflow2/data/logs:/opt/bitnami/airflow/logs'
  airflow:
    image: bitnami/airflow:2
    container_name: airflow_webserver
    environment:
      AIRFLOW_DATABASE_NAME: bitnami_airflow
      AIRFLOW_DATABASE_USERNAME: bn_airflow
      AIRFLOW_DATABASE_PASSWORD: **masked**
      AIRFLOW_EXECUTOR: CeleryExecutor
      AIRFLOW_LOAD_EXAMPLES: "no"
      AIRFLOW_BASE_URL: https://airflow.**masked**.co.uk
      AIRFLOW__WEBSERVER__BASE_URL: https://airflow.**masked**.co.uk
      AIRFLOW_SECRET_KEY: **masked**
      AIRFLOW_USERNAME: **masked**
      AIRFLOW_PASSWORD: **masked**
      AIRFLOW_EMAIL: dtomlinson@**masked**.co.uk
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/mnt/user/appdata/airflow2/dags:/opt/bitnami/airflow/dags'
      - '/mnt/user/appdata/airflow2/requirements.txt"/bitnami/python/requirements.txt'
      - '/mnt/user/appdata/airflow2/data/logs:/opt/bitnami/airflow/logs'
    ports:
      - '8001:8080'
```

when bringing up the stack from a previous installation on 2.2.5.

### What is the expected behavior?

The worker & scheduler should both come up & connect to the database

The message

```
The scheduler does not appear to be running. Last heartbeat was received 1 minute ago.

The DAGs list may not update, and new tasks will not be scheduled.
```

Should not appear when logging in.

### What do you see instead?

The worker & scheduler containers crash because they cannot connect to the database.

Logs from the scheduler (the worker shows the same error):

```
airflow-scheduler 02:06:19.26 
airflow-scheduler 02:06:19.27 Welcome to the Bitnami airflow-scheduler container
...
airflow-scheduler 02:06:19.28 INFO  ==> Enabling non-root system user with nss_wrapper
airflow-scheduler 02:06:19.29 INFO  ==> ** Starting Airflow setup **
airflow-scheduler 02:06:19.36 INFO  ==> No injected configuration file found. Creating default config file
airflow-scheduler 02:06:20.40 INFO  ==> Configuring Airflow database
airflow-scheduler 02:06:20.46 INFO  ==> Configuring Celery Executor
airflow-scheduler 02:06:20.50 INFO  ==> Trying to connect to the database server
airflow-scheduler 02:07:25.29 ERROR ==> Could not connect to the database
```

Logs from postgres container:

```
postgresql 02:06:19.54 
postgresql 02:06:19.54 Welcome to the Bitnami postgresql container
...
postgresql 02:06:19.77 INFO  ==> ** Starting PostgreSQL **
2022-05-07 02:06:19.840 GMT [1] LOG:  pgaudit extension initialized
2022-05-07 02:06:19.841 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-05-07 02:06:19.841 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2022-05-07 02:06:19.853 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-05-07 02:06:19.913 GMT [85] LOG:  database system was shut down at 2022-05-07 02:05:56 GMT
2022-05-07 02:06:19.922 GMT [1] LOG:  database system is ready to accept connections
```

### Additional information

Reverting to images:

```
bitnami/airflow-worker:2.2.5-debian-10-r25
bitnami/airflow-scheduler:2.2.5-debian-10-r25
```

and the worker & scheduler both come up and connect just fine.

For now, I've fixed all 3 images to this tag but the latest tags (`:2`) do not work.

It seems `r25` was the last version on `2.2.5`, the containers after that look to be `2.3`.
