### ISSUE TITLE
Issue with docker-compose setup

### ISSUE THREAD

**Issue by stejul** [bitnami/bitnami-docker-airflow#137]
### Name and Version

bitnami/airflow:2.2.5; bitnami/airflow-scheduler:2.2.5; bitnami/airflow-worker:2.2.5

### What steps will reproduce the bug?

```yaml
  # Airflow
  airflow:
    image: bitnami/airflow:2.2.5
    container_name: "airflow"
    ports:
      - "8080:8080"
    env_file:
      - openlineage.env
    environment:
      - AIRFLOW_USERNAME=${AIRFLOW_USER}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_EMAIL=airfloow@example.com
      - AIRFLOW_FERNET_KEY=Z2uDm0ZL60fXNkEXG8LW99Ki2zf8wkmIltaTz1iQPDU=
      - AIRFLOW_DATABASE_HOST=db
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DB}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_USER}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_CONN_EXAMPLE_DB=postgres://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@db:5432/${AIRFLOW_DB}
    volumes:
      - ./realestatescrape/dags:/opt/bitnami/airflow/dags
      - ${PWD}/realestatescrape/whl:/whl
      - type: bind
        source: ${PWD}/requirements.txt
        target: /bitnami/python/requirements.txt

  airflow_scheduler:
    image: bitnami/airflow-scheduler:2.2.5
    container_name: "airflow-scheduler"
    env_file:
      - openlineage.env
    environment:
      - AIRFLOW_FERNET_KEY=Z2uDm0ZL60fXNkEXG8LW99Ki2zf8wkmIltaTz1iQPDU=
      - AIRFLOW_DATABASE_HOST=db
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DB}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_USER}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_CONN_EXAMPLE_DB=postgres://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@db:5432/${AIRFLOW_DB}
    volumes:
      - ./realestatescrape/dags:/opt/bitnami/airflow/dags
      - ${PWD}/realestatescrape/whl:/whl
      - type: bind
        source: ${PWD}/requirements.txt
        target: /bitnami/python/requirements.txt

  airflow_worker:
    image: bitnami/airflow-worker:2.2.5
    container_name: "airflow-worker"
    env_file:
      - openlineage.env
    environment:
      - AIRFLOW_FERNET_KEY=Z2uDm0ZL60fXNkEXG8LW99Ki2zf8wkmIltaTz1iQPDU=
      - AIRFLOW_DATABASE_HOST=db
      - AIRFLOW_DATABASE_NAME=${AIRFLOW_DB}
      - AIRFLOW_DATABASE_USERNAME=${AIRFLOW_USER}
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_CONN_EXAMPLE_DB=postgres://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@db:5432/${AIRFLOW_DB}
    volumes:
      - ./realestatescrape/dags:/opt/bitnami/airflow/dags
      - ${PWD}/realestatescrape/whl:/whl
      - type: bind
        source: ${PWD}/requirements.txt
        target: /bitnami/python/requirements.txt

  redis:
    container_name: "airflow-redis"
    image: bitnami/redis:6.0.6
    environment:
      - ALLOW_EMPTY_PASSWORDS=yes

  db:
    image: bitnami/postgresql:12.1.0
    container_name: marquez-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MARQUEZ_DB=${MARQUEZ_DB}
      - MARQUEZ_USER=${MARQUEZ_USER}
      - MARQUEZ_PASSWORD=${MARQUEZ_PASSWORD}
      - AIRFLOW_DB=${AIRFLOW_DB}
      - AIRFLOW_USER=${AIRFLOW_USER}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
      - EXAMPLE_USER=example
      - EXAMPLE_PASSWORD=example
      - EXAMPLE_DB=example
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

```

### What is the expected behavior?

By following the guide I saw on the docker hub the services should work correctly and no issues should be present.

### What do you see instead?

The airflow-scheduler and airflow-worker dont' seem to connect to the webserver. Is there something wrong with the configuration

### Additional information

I'm trying to set up a airflow and marquez environment in docker. I think the airflow configuration should be correct but the scheduler and worker are always exiting or have the following status `timeout reached before the port went into state "inuse"`
