### ISSUE TITLE
Cannot install from requirements.txt because redis version is too high...

### ISSUE THREAD

**Issue by VBoB13** [bitnami/bitnami-docker-airflow#138]
### Name and Version

bitnami/airflow:2

### What steps will reproduce the bug?

1. With this docker-compose.yml:
```
version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - redis_data:/bitnami
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
  # image: w1ck3d/lowi5-airflow-scheduler:latest
    build:
      context: .
      dockerfile: airflow-scheduler/Dockerfile 
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no    
    volumes:
      - airflow_scheduler_data:/bitnami
      - /var/run/docker.sock:/var/run/docker.sock
  airflow-worker:
  # image: w1ck3d/lowi5-airflow-worker:latest
    build:
      context: .
      dockerfile: airflow-worker/Dockerfile 
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no 
    volumes:
      - airflow_worker_data:/bitnami
      - /var/run/docker.sock:/var/run/docker.sock 
  airflow:
  # image: w1ck3d/lowi5-airflow:latest
    build:
      context: .
      dockerfile: airflow/Dockerfile
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - airflow_data:/bitnami
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - 8080:8080
volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
```
In which each Dockerfile looks like this:
```
FROM bitnami/airflow:2
CMD ["python", "-m", "pip", "install", "--upgrade", "pip"]
COPY python /bitnami/python
COPY dags /opt/bitnami/airflow/dags
COPY Lowi5 /opt/Lowi50/Lowi5
```

The `airflow-worker` and `airflow-scheduler` containers also have identical Dockerfiles (except their original image, of course).

```
FROM bitnami/airflow-worker:2
(same as above)
```
and
```
FROM bitnami/airflow-scheduler2
(same as above)
```

### What is the expected behavior?

I expected `pip` to upgrade first in hopes that the upgraded `pip` would be able to resolve the dependency issue caused by `redis` being too new. Since the images `bitnami/airflow:2` etc. all install according to the `requirements.txt` you provide, I make sure to use `COPY` **AFTER** I have upgraded `pip`, but that does not work...

### What do you see instead?

I end up with an error from each container saying:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
apache-airflow-providers-redis 2.0.4 requires redis~=3.2, but you have redis 4.2.2 which is incompatible.
```

### Additional information

Not sure if there's anything to add... I'm a beginner at Docker AND Airflow, so let me know if there are more details that you need.

**Comment by fmulero** [comment]
Hi Richard, thanks a lot for using bitnami images.

I think your problem is here:
```
CMD ["python", "-m", "pip", "install", "--upgrade", "pip"]
```
In a Dockerfile you can find instructions to build your container (`FROM`, `ARGS`, `COPY`, `RUN`, etc) or instructions about the execution of your container (`ENTRYPOINT`, `CMD`, `ENV`, etc ).
In your case you need to **build** an image with a new version of pip, so you should change the [CMD](https://docs.docker.com/engine/reference/builder/#cmd) instruction to [RUN](https://docs.docker.com/engine/reference/builder/#run)

[Here](https://docs.docker.com/engine/reference/builder/#run) you've got an example about how to extend one of our images.

I hope it helps

**Comment by VBoB13** [comment]
I changed my Dockerfiles to the following:
```
FROM bitnami/airflow:2
USER root
RUN ["python", "-m", "pip", "install", "--upgrade", "pip"]
COPY python /bitnami/python
COPY dags /opt/bitnami/airflow/dags
COPY Lowi5 /opt/Lowi50/Lowi5
```
Despite this, I get the following messages in the beginning of my logs:
```
airflow 03:21:06.49 INFO  ==> Enabling non-root system user with nss_wrapper
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
```

And the `redis` problem is still mentioned at the end:
```
Successfully built bs4 fake-useragent parse user-agent demjson3 pbkdf2 pyaes
Installing collected packages: tzdata, backports.zoneinfo, websockets, tqdm, pytz-deprecation-shim, pyee, multidict, frozenlist, cssselect, certifi, yarl, w3lib, tzlocal, regex, pyquery, pyppeteer, parse, fake-useragent, bs4, aiosignal, requests-html, pycryptodome, pyaes, pbkdf2, lz4, et-xmlfile, demjson3, dateparser, aiohttp, user-agent, playwright, pillow, openpyxl, line-bot-sdk, Flask-Executor, facebook-scraper, et, chardet, browser-cookie3, apscheduler
  Attempting uninstall: certifi
    Found existing installation: certifi 2020.12.5
    Uninstalling certifi-2020.12.5:
      Successfully uninstalled certifi-2020.12.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
apache-airflow-providers-redis 2.0.4 requires redis~=3.2, but you have redis 4.2.2 which is incompatible.
```

What do I need to change? o.O

**Comment by VBoB13** [comment]
Update:

As I am a beginner and thought that maybe it's the system package of `redis` that I need to install by copying over a .tar.gz file of `redis` and then installing it in each container. That did not work. The `redis` problem still persists.
Then I tried to add the line:
```
...
RUN ["python", "-m", "pip", "install", "redis~=3.2"]
...
```
but there was no luck there either...
I'm starting to run out of thinkable options here for my beginner brain... please, expert Bitnami people, help :)

**Comment by fmulero** [comment]
Hi Ricahrd, maybe we need to start from the beginning. What are you trying to achieve? 

If you need to install new pip modules, you can do it directly with our images, mounting your `requirements.txt` file in `/bitnami/python/requirements.txt`:
```
...
  airflow:
    image: bitnami/airflow:latest
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - './requirements.txt:/bitnami/python/requirements.txt'
    ports:
      - '8080:8080'
...
```

The content of the requirements.txt file should follow this [format](https://pip.pypa.io/en/stable/reference/requirements-file-format/)
