### ISSUE TITLE
Get "Permission Denied" when calling DockerOperator

### ISSUE THREAD

**Issue by VioletVivirand** [bitnami/bitnami-docker-airflow#17]
**Description**

Hi guys! I gonna use [Docker Operator](https://airflow.apache.org/_api/airflow/operators/docker_operator/index.html) inside [bitnami-docker-airflow-worker](https://github.com/bitnami/bitnami-docker-airflow-worker), but gets `permission denied` message returned. I've tried to add `-u $(id -u root)` or `-u 0`([Reference](https://github.com/bitnami/bitnami-docker-postgresql/issues/87#issuecomment-427769669)) when creating container but still no use.

Could somebody make a suggestion? Thanks!

**Steps to reproduce the issue:**

If I add `user: root` into `docker-compose.yml`, and view the logs by executing `docker logs -f airflow-worker`:

```bash
NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/opt/bitnami/airflow/nss_passwd' readonly -1:No such file or directory
NWRAP_ERROR(1) - nwrap_files_getpwuid: Error loading passwd file

Welcome to the Bitnami airflow-worker container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow-worker
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow-worker/issues

nami    INFO  Initializing airflow-worker
airflow INFO  ==> No injected configuration files found. Creating default config file...
airflow INFO  ==> Configuring Airflow database...
airflow INFO  ==> Configuring Airflow Celery Executor...
airflow INFO  ==> Deploying Airflow with persisted data...
Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/airflow-worker/data'
```

And I am calling `docker-py` to demonstrate what happened when non-root user trying to use docker:

1. Run container and bind `docker.sock`: `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock bitnami/airflow-worker:1.10.6-debian-9-r0 bash`⮐
1. Activate Virtualenv: `source /opt/bitnami/airflow/venv/bin/activate`⮐
1. Open Python REPL: `python` ⮐
1. Try to use `docker-py` to connect Docker endpoint:

```python
>>> import docker
>>> client = docker.DockerClient(base_url='unix://var/run/docker.sock')
>>> client.info()
...
...
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))
```

**Comment by andresbono** [comment]
Can you remove the volumes and try to deploy the docker-compose again? Maybe doing it from scratch works.

**Comment by leobenkel** [comment]
how did you solve the issue here?

**Comment by andresbono** [comment]
Hi @leobenkel, are you facing the same issue? We never got an answer from @VioletVivirand, so we don't know if this was solved or not.

**Comment by leobenkel** [comment]
Yes, I am getting the same error.

**Comment by andresbono** [comment]
Ok, we are reopening the issue then.

Did you try this already? https://github.com/bitnami/bitnami-docker-airflow/issues/17#issuecomment-554363188

**Comment by leobenkel** [comment]
Yes several times

**Comment by leobenkel** [comment]
I think it is a port issue. docker is trying to pull from ECR and the ports are not open but I can't find any documentation on what port to open and I don't know how to add more debug print logs in airflow to tell me what connection has failed

**Comment by andresbono** [comment]
Does it make sense that you ask about it in the Airflow Community channels? 

https://airflow.apache.org/community/ 

Do you think the issue is somehow related to the way the Bitnami container is configured?

**Comment by leobenkel** [comment]
no, I think it is related to my own airflow set up not allowing ECR to talk to the internet, the error I get is : 

```
[2020-01-29 22:40:52,576] {{docker_operator.py:201}} INFO - Starting docker container from image XXXXXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/org/image:tag
[2020-01-29 22:40:52,612] {{logging_mixin.py:112}} INFO - [2020-01-29 22:40:52,612] {{base_hook.py:84}} INFO - Using connection to: id: docker_ecr. Host: https://XXXXXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com, Port: None, Schema: None, Login: AWS, Password: XXXXXXXX, extra: {'reauth': 'no'}
[2020-01-29 22:40:52,618] {{taskinstance.py:1058}} ERROR - ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by andresbono** [comment]
Yes, looking at the error message, it could be the reason.

Maybe you can try in a different host just for testing purposes.

**Comment by leobenkel** [comment]
AWS support told me to try to forward port 443 since it is https connection. I havent had the time to try. I dont think it will work, but i'll try.

**Comment by nixonraphy** [comment]
I'm facing a similar scenario , while using docker operator .

Strangely , when i invoke the workflow using the command-line option "airflow run ", individual tasks are getting triggered . However, when I use "airflow trigger-dag" option to invoke the same workflow , leads to "Permission denied" Errors .

Both commands are run using the same username on linux env and the user if part of the docker group. User can access docker commands as well.

[2020-02-06 13:48:04,576] {docker_operator.py:201} INFO - Starting docker container from image pi:sample
[2020-02-06 13:48:04,579] {taskinstance.py:1058} ERROR - ('Connection aborted.', PermissionError(13, 'Permission denied'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/username/.local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

**Comment by leobenkel** [comment]
it did not work haha

**Comment by andresbono** [comment]
What about trying in a differnt host? Can you try in your local machine to see how it behaves?

**Comment by leobenkel** [comment]
locally it works fine. no problem at all. with the same credentials that the airflow container has

**Comment by andresbono** [comment]
Well, that's some progress! Maybe you should verify the port configuration in your ECR instance.

**Comment by BDubas** [comment]
Not sure if this is still relevant, but I'm having similar issue.
And it looks like the root cause comes from user permissions.
I can run docker from airflow container with "root" user, but "airflow" user fails with PermissionDenied.

root:
```
>>> import docker
>>> c = docker.from_env()
>>> c.containers.run("container/name", "python3 /app/sleep.py")
b''
```

airflow:
```
>>> import docker
>>> c = docker.from_env()
>>> c.containers.run("container/name", "python3 /app/sleep.py")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied
```

**Comment by BDubas** [comment]
Yeah, that was the case for me, changing permission to docker socket worked:
```
chmod 777 /var/run/docker.sock
```

**Comment by andresbono** [comment]
Thanks @BDubas for providing this workaround. Users will benefit from it.

**Comment by pablobmc** [comment]
chmod 777 /var/run/docker.sock doesn't  work for me,
deploy from scratch doesn't work either

**Comment by carrodher** [comment]
Hi, in order to try to reproduce the issue on our side, can you provide more information about your specific use case?:

What image are you using? In a docker-compose? What are the changes/steps you are doing when the issue is faced? Thanks

**Comment by pablobmc** [comment]
> Hi, in order to try to reproduce the issue on our side, can you provide more information about your specific use case?:

hi, i use a docker-compose file,
I solved my issue by setting a user for worker, scheduler and webserver  in my compose-file, but now i have another issue.
The scheduler and worker is not running when i deploy.
if i run "airflow worker" or "airflow scheduler" inside their containers then it works.



--------------
Pido perdón por mi inglés. 
Si es que no se entiende, lo escribo también en español.

Estoy usando un compose-file.
Solucioné el problema asignando un usuario para el worker, scheduler y webserver, pero tengo otro problema ahora, y es que el scheduler y el worker no inician después de realizar el deploy.
Si ingreso a sus respectivos contenedores y lanzo el comando "airflow worker" o "airflow shceduler" funciona, pero este proceso  debiese ser automático.
dejo un ejemplo de mi compose-file a continuación.

-----------

````
version: '3.7'
services:

  postgresql:
    image: 'docker.io/bitnami/postgresql:10-debian-10'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=airflow
      - POSTGRESQL_USERNAME=bdUser
      - POSTGRESQL_PASSWORD=dbPass
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default

  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- redis_data:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default

  scheduler:
    image: docker.io/bitnami/airflow-scheduler:1-debian-10
    user: MyUSER
    environment:
      - AIRFLOW_FERNET_KEY=MyFernetKey
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=dbUser
      - AIRFLOW_DATABASE_PASSWORD=dbPass
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./My/Dags/Folder:/opt/bitnami/airflow/dags
      #- airflow_scheduler_data:/bitnami
    networks:
      - default 

  worker:
    image: docker.io/bitnami/airflow-worker:1-debian-10
    user: MyUser
    environment:
      - AIRFLOW_FERNET_KEY=MyFernetKey
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=dbUser
      - AIRFLOW_DATABASE_PASSWORD=dbPass
      - AIRFLOW_EXECUTOR=CeleryExecutor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./My/Dags/Folder:/opt/bitnami/airflow/dags
      #- airflow_worker_data:/bitnami
    networks:
      - default

  webserver:
    image: docker.io/bitnami/airflow:1-debian-10
    user: MyUser
    environment:
      - AIRFLOW_FERNET_KEY=MyFernetKey
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=dbUser
      - AIRFLOW_DATABASE_PASSWORD=dbPass
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_USERNAME=adminUserName
      - AIRFLOW_PASSWORD=adminPassword
      - AIRFLOW_FIRSTNAME=adminFirs
      - AIRFLOW_LASTNAME=adminLast
      - AIRFLOW_EMAIL=admin@email.cl
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=America/Santiago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./My/Dags/Folder:/opt/bitnami/airflow/dags
      #- airflow_data:/bitnami
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/bitnami/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3


networks:
  default:
      external:
          name: MyNetwork

#volumes:
#  airflow_scheduler_data:
#    driver: local
#  airflow_worker_data:
#    driver: local
#  airflow_data:
#    driver: local
#  postgresql_data:
#    driver: local
#  redis_data:
#    driver: local
```
