### ISSUE TITLE
Custom DAGs in running state but internal tasks don't start (queued)

### ISSUE THREAD

**Issue by informatica92** [bitnami/bitnami-docker-airflow#42]
**Description**

Only example DAGs are executed properly. If I try to run a custom DAG instead, the DAG becomes "running" but no one of the tasks inside is queued.

**Steps to reproduce the issue:**
***my docker-compose.yml file:***
```
version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:10'
    restart: always
    volumes:
      - '/var/lib/docker/volumes/bitnami-airflow_postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: bitnami/redis:5.0
    restart: always
    volumes:
      - '/var/lib/docker/volumes/bitnami-airflow_redis_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  airflow-scheduler:
    image: bitnami/airflow-scheduler:1
    restart: always
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    volumes:
      - '/var/lib/docker/volumes/bitnami-airflow_airflow_scheduler_data:/bitnami'

  airflow-worker:
    image: bitnami/airflow-worker:1
    restart: always
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    volumes:
      - '/var/lib/docker/volumes/bitnami-airflow_airflow_worker_data:/bitnami'

  airflow:
    image: bitnami/airflow:1
    restart: always
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - '8080:8080'
    volumes:
      - '/var/lib/docker/volumes/bitnami-airflow_airflow_data:/bitnami'
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
```
***my hello_world.py file in the .dags/ folder:***
```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator
#from custom_operator.hello_operator import HelloOperator
from airflow.operators                 import HelloOperator

def print_hello():
 return 'Hello Wolrd'

dag = DAG('hello_world', description='Hello world example', schedule_interval='0 12 * * *', start_date=datetime(2017, 3, 20), catchup=False)

dummy_operator = DummyOperator(task_id='dummy_task', retries = 3, dag=dag)

hello_operator = PythonOperator(task_id='hello_task', python_callable=print_hello, dag=dag)

hello_task = HelloOperator(task_id='sample-task', name='foo_bar', dag=dag)

dummy_operator >> hello_operator >> hello_task
```

1. run sudo docker-compose up -d
2. go to the http://<ip_address>:8080
3. trigger an example DAG and my hello_world DAG

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/17550961/81905974-c84ff280-95c5-11ea-9bbb-9e2b01c0dbea.png)

**Describe the results you expected:**

Also for the hello_world DAG, the internal task should run

**Additional information you deem important (e.g. issue happens only occasionally):**

It happens only with DAGs created by me

**Version**

- Output of `docker version`:

```
sudo docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

- Output of `docker info`:

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
m.riezzo@airflow-docker:~/bitnami-airflow$ sudo docker info
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: btrna5ha16okj6003f4h88295
  Is Manager: true
  ClusterID: mj08kpmf7o5xyyr0e94cjgy84
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.132.0.20
  Manager Addresses:
   10.132.0.20:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1009-gcp
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.597GiB
 Name: airflow-docker
 ID: CVAT:NDID:XDYQ:M7MA:DN2Z:WW2J:5MDW:HHGO:AGB2:45WH:H7HF:NMZD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
I am running this on a Google Cloud Platform VM instance (n1-standard-1)
