### ISSUE TITLE
Permissions Error when Mounting Host Directories

### ISSUE THREAD

**Issue by nyxynyx** [bitnami/bitnami-docker-airflow#45]
**Description**

Every docker container that mounts a host directory will have a permissions-related error.

**Steps to reproduce the issue:**

1. Create the following `docker-compose.yml` based on the example in README.md

```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    volumes:
      - ./postgresql:/bitnami/postgresql
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis:/bitnami
  airflow-worker:
    image: bitnami/airflow-worker:latest
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes
    volumes:
      - ./airflow-worker:/bitnami
  airflow-scheduler:
    image: bitnami/airflow-scheduler:latest
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes
    volumes:
      - ./airflow-scheduler:/bitnami
  airflow:
    image: bitnami/airflow:latest
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
    ports:
      - '8080:8080'
    volumes:
      - ./airflow:/bitnami
```

2. `docker-compose up -d`

**Describe the results you received:**

1. Error in `redis`

```
$ docker logs airflow_redis_1

 16:32:31.40 Welcome to the Bitnami redis container
 16:32:31.40 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
 16:32:31.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
 16:32:31.41 
 16:32:31.41 INFO  ==> ** Starting Redis setup **
 16:32:31.42 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
 16:32:31.43 INFO  ==> Initializing Redis...
mkdir: cannot create directory '/bitnami/redis': Permission denied
```

2. *Error in `postgres`

```
$ docker logs airflow_postgresql_1

postgresql 16:32:33.61 
postgresql 16:32:33.61 Welcome to the Bitnami postgresql container
postgresql 16:32:33.61 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 16:32:33.62 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 16:32:33.62 
postgresql 16:32:33.63 INFO  ==> ** Starting PostgreSQL setup **
postgresql 16:32:33.69 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 16:32:33.70 INFO  ==> Loading custom pre-init scripts...
postgresql 16:32:33.71 INFO  ==> Initializing PostgreSQL database...
mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
postgresql 16:32:33.72 INFO  ==> Stopping PostgreSQL...
```

3. Containers for `airflow`, `airflow-scheduler` and `airflow-worker` cannot connect to PostgreSQL.

```
...

airflow INFO  ==> No injected configuration files found. Creating default config file...
airflow INFO  ==> Configuring Airflow database...
airflow INFO  ==> Setting Airflow Fernet key...
airflow INFO  ==> Configuring Airflow Celery Executor...
airflow INFO  ==> Deploying Airflow from scratch...
postgre INFO  Trying to connect to PostgreSQL server
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:30 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on Ubuntu 18.04
