### ISSUE TITLE
Set our own User UID?

### ISSUE THREAD

**Issue by vertangelx** [bitnami/bitnami-docker-airflow#46]
**Description**

How can we set our own user UID when running the docker-compose.yml on Ubuntu 20.04?

**Describe the results you expected:**

It will be ideal to be able to define the user UID instead of the default 1001.

https://github.com/bitnami/bitnami-docker-airflow/blob/master/1/debian-10/Dockerfile#L79

Maybe give us a way to rebuild the image with the UID that we like?

```
services:
    airflow:
        image: bitnami/airflow:1
        build:
            context: .
            args:
                - DOCKER_UID=${DOCKER_UID} 
            dockerfile: Dockerfile

```

I need to change the user UID from 1001 to a specific user because my DAGs contain tasks that involve reading/writing files on the host system (mounted host directories) as that specific user. 

Additionally, is the changing of UID only required in the worker container? I can use either LocalExecutor or CeleryExecutor.
