### ISSUE TITLE
On-failure email's URL to Log leads to 404

### ISSUE THREAD

**Issue by levihernan** [bitnami/bitnami-docker-airflow#57]
When receiving a failure email: 

Try 1 out of 1
Exception:
Bash command failed
Log: Link
Host: f6f8a1cba198
Log file: /opt/bitnami/airflow/logs/email_test/always_fail/2020-10-26T17:47:50.022899+00:00.log
Mark success: Link

The Link for entering the Log has this shape:
http://<SERVER>:<PORT>/admin/airflow/log?execution_date=<EXEC_DATE>&task_id=<TASK>&dag_id=<DAG>

This URL leads to a 404 page. While if removing the "/admin/airflow" the link works OK:
http://<SERVER>:<PORT>/log?execution_date=<EXEC_DATE>&task_id=<TASK>&dag_id=<DAG>

I cannot find a configuration to change this.

**Comment by rafariossaa** [comment]
Hi,
  Could you provide steps to reproduce the issue ? I would like to set a similar scenario. 
  I guess that in the URLs provided you have removed the host and port, isn't it ?

**Comment by levihernan** [comment]
Hello Rafael,
For sure I'll try.

I'm running a Bitnami Docker with the following docker-compose:

```
version: '2'

services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:10-debian-10'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=<DB NAME>
      - POSTGRESQL_USERNAME=<DB USER>
      - POSTGRESQL_PASSWORD=<DB PASSWORD>
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    volumes:
      - 'redis_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:1-debian-10
    environment:
      - AIRFLOW__CORE__PARALLELISM=8
      - AIRFLOW__CORE__DAG_CONCURRENCY=8
      - AIRFLOW__CORE__CONCURRENCY=4
      - AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=4
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=false
      - AIRFLOW_DATABASE_NAME=<DB NAME>
      - AIRFLOW_DATABASE_USERNAME=<DB USER>
      - AIRFLOW_DATABASE_PASSWORD=<DB PASSWORD>
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - AIRFLOW__CORE__FERNET_KEY=<FERNET KEY>
      # EMAIL CONFIG
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=<EMAIL>
      - AIRFLOW__SMTP__SMTP_PASSWORD=<EMAIL PASSWORD>
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=<EMAIL>
      # ENDPOINT
      - AIRFLOW__CLI__ENDPOINT_URL=http://<SERVER IP>:8080/
      - AIRFLOW__WEBSERVER__BASE_URL=http://<SERVER IP>:8080/

    volumes:
      - airflow_scheduler_data:/bitnami
      - <...>
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:1-debian-10
    environment:
      - AIRFLOW__CORE__PARALLELISM=8
      - AIRFLOW__CORE__DAG_CONCURRENCY=8
      - AIRFLOW__CORE__CONCURRENCY=4
      - AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=4
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=false
      - AIRFLOW_DATABASE_NAME=<DB NAME>
      - AIRFLOW_DATABASE_USERNAME=<DB USER>
      - AIRFLOW_DATABASE_PASSWORD=<DB PASSWORD>
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - AIRFLOW__CORE__FERNET_KEY=<FERNET KEY>
      # EMAIL CONFIG
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=<EMAIL>
      - AIRFLOW__SMTP__SMTP_PASSWORD=<EMAIL PASSWORD>
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=<EMAIL>
      # ENDPOINT
      - AIRFLOW__CLI__ENDPOINT_URL=http://<SERVER IP>:8080/
      - AIRFLOW__WEBSERVER__BASE_URL=http://<SERVER IP>:8080/
    volumes:
      - airflow_worker_data:/bitnami
      - <...>
  airflow:
    image: docker.io/bitnami/airflow:1-debian-10
    environment:
      - AIRFLOW__CORE__PARALLELISM=8
      - AIRFLOW__CORE__DAG_CONCURRENCY=8
      - AIRFLOW__CORE__CONCURRENCY=4
      - AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=4
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=false
      - AIRFLOW_DATABASE_NAME=<DB NAME>
      - AIRFLOW_DATABASE_USERNAME=<DB USER>
      - AIRFLOW_DATABASE_PASSWORD=<DB PASSWORD>
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - AIRFLOW__CORE__FERNET_KEY=<FERNET KEY>
      # EMAIL CONFIG
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=<EMAIL>
      - AIRFLOW__SMTP__SMTP_PASSWORD=<EMAIL PASSWORD>
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=<EMAIL>
      # ENDPOINT
      - AIRFLOW__CLI__ENDPOINT_URL=http://<SERVER IP>:8080/
      - AIRFLOW__WEBSERVER__BASE_URL=http://<SERVER IP>:8080/
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami
      - <...>
volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
```


Then a DAG with the following code:
```
from datetime import timedelta, datetime

from airflow.models import DAG
from airflow.operators.bash_operator import BashOperator
from airflow.operators.dummy_operator import DummyOperator

from airflow.utils.dates import days_ago

default_args = {
    'owner': 'Airflow',
    'start_date': datetime.strptime('2020-10-26', '%Y-%m-%d'),
    # 'depends_on_past':False,
    # 'wait_for_downstream':True,
    'retries':0,
    #'retry_delay': timedelta(minutes=1),
    'email': ['<EMAIL>'],
    'email_on_failure': True
}

with DAG(
    dag_id='email_test',
    default_args=default_args,
    schedule_interval='0 0 * * *',
    dagrun_timeout=timedelta(minutes=60),
    tags=['test']
) as dag:

    dummy_task = DummyOperator(task_id='dummy_task')

    t1 = BashOperator(
      task_id='always_fail',
      bash_command='exit(1)',
      #dag=dag
    )


    dummy_task >> t1
```


And when receiving the email, as tried to explain in the issue, it brings a link to the Log that sends me to a 404 page.
When checking on the URL that should bring me to the Log, I've detected that the URL has an extra **/admin/airflow** that if I remove it from the URL it works just fine:

This leads me to 404:
`http://<SERVER IP>:8080/admin/airflow/log?execution_date=2020-10-27T10%3A00%3A00%2B00%3A00&task_id=always_fail&dag_id=email_test`

This works just fine:
`http://<SERVER IP>:8080/log?execution_date=2020-10-27T10%3A00%3A00%2B00%3A00&task_id=always_fail&dag_id=email_test`

Hope this is reproduceable!
Thanks for your reply,
Bests!
HL
