### ISSUE TITLE
No module named 'elasticsearch'

### ISSUE THREAD

**Issue by armandleopold** [bitnami/bitnami-docker-airflow#58]
Hello,

I am unable to install elasticsearch dependencies to the bitnami image.
I want to use ES as a external logging endpoint with my Airflow on KubernetesExecutor Mode.
Is there something i am doing wrong with the venv ?

```
FROM docker.io/bitnami/airflow:1.10.12-debian-10-r41

ENV VIRTUAL_ENV=/opt/bitnami/airflow/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install elasticsearch
```
Thanks

**Comment by FraPazGal** [comment]
Hello @armandleopold,

This image supports installing additional modules at installation time mounting a `requirements.txt` file, I think that would be easier than modifying the image. Please take a look at [this section](https://github.com/bitnami/bitnami-docker-airflow/blob/4f17ac2a6b6ff9fc594676fe2840c6086a9120a3/README.md#installing-additional-python-modules) of our README for more info.

If you have to modify the image, you would need to run the commands as root:

```Dockerfile
FROM docker.io/bitnami/airflow:1.10.12-debian-10-r41

USER 0

ENV VIRTUAL_ENV=/opt/bitnami/airflow/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install elasticsearch

USER 1001
```

**Comment by armandleopold** [comment]
It seems that the container start first with airflow and after that it installs dependencies.

It should be great if the dependencies were to be installed BEFORE instanciating airflow.

```
Welcome to the Bitnami airflow container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow/issues
nami    INFO  Initializing airflow
airflow INFO  ==> No injected configuration files found. Creating default config file...
Error executing 'postInstallation': Unable to load the config, contains a configuration error.
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/logging/config.py", line 390, in resolve
    found = getattr(found, frag)
AttributeError: module 'airflow.utils.log' has no attribute 'es_task_handler'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/logging/config.py", line 392, in resolve
    self.importer(used)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/log/es_task_handler.py", line 21, in <module>
    import elasticsearch
ModuleNotFoundError: No module named 'elasticsearch'
```

**Comment by armandleopold** [comment]
Actually if i am overriding the CMD to sleep 3600 and executing a shell on the pod, then running ./run.sh,
it actually runs the dependencies installation. Then failes to other things.
For information i am using you Helm Chart bitnami/airflow

Stack Trace 
```
I have no name!@airflow-deployement-web-77d57db8b9-6sps5:/$ ls
airflow-inputs.json  app-entrypoint.sh  bin  bitnami  boot  build  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  run.sh  sbin  srv  sys  tmp  usr  var
I have no name!@airflow-deployement-web-77d57db8b9-6sps5:/$ ls /bitnami/python/
requirements.txt
I have no name!@airflow-deployement-web-77d57db8b9-6sps5:/$ cat /bitnami/python/requirements.txt 
elasticsearch
elasticsearch_dsl
I have no name!@airflow-deployement-web-77d57db8b9-6sps5:/$ ls
airflow-inputs.json  app-entrypoint.sh  bin  bitnami  boot  build  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  run.sh  sbin  srv  sys  tmp  usr  var
I have no name!@airflow-deployement-web-77d57db8b9-6sps5:/$ ./run.sh 
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting elasticsearch
  Downloading elasticsearch-7.9.1-py2.py3-none-any.whl (219 kB)
     |████████████████████████████████| 219 kB 5.4 MB/s 
Collecting elasticsearch_dsl
  Downloading elasticsearch_dsl-7.3.0-py2.py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 15.1 MB/s 
Requirement already satisfied: certifi in /opt/bitnami/airflow/venv/lib/python3.6/site-packages (from elasticsearch->-r /bitnami/python/requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: urllib3>=1.21.1 in /opt/bitnami/airflow/venv/lib/python3.6/site-packages (from elasticsearch->-r /bitnami/python/requirements.txt (line 1)) (1.25.11)
Requirement already satisfied: python-dateutil in /opt/bitnami/airflow/venv/lib/python3.6/site-packages (from elasticsearch_dsl->-r /bitnami/python/requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: six in /opt/bitnami/airflow/venv/lib/python3.6/site-packages (from elasticsearch_dsl->-r /bitnami/python/requirements.txt (line 2)) (1.15.0)
Installing collected packages: elasticsearch, elasticsearch-dsl
Successfully installed elasticsearch-7.9.1 elasticsearch-dsl-7.3.0
WARNING: You are using pip version 20.2.2; however, version 20.2.4 is available.
You should consider upgrading via the '/opt/bitnami/airflow/venv/bin/python -m pip install --upgrade pip' command.
Waiting for db...
Database is ready
INFO  ==> Starting airflow...
tee: /opt/bitnami/airflow/logs/airflow-webserver.log: No such file or directory
[2020-11-04 13:02:13,786] {cli_action_loggers.py:107} WARNING - Failed to log action with (sqlite3.OperationalError) no such table: log
[SQL: INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2020-11-04 13:02:13.780917', None, None, 'cli_webserver', None, 'airflow', '{"host_name": "airflow-deployement-web-77d57db8b9-6sps5", "full_command": "[\'/opt/bitnami/airflow/venv/bin/airflow\', \'webserver\']"}')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2020-11-04 13:02:13,941] {__init__.py:50} INFO - Using executor SequentialExecutor
[2020-11-04 13:02:13,942] {dagbag.py:417} INFO - Filling up the DagBag from /opt/bitnami/airflow/dags
```

**Comment by FraPazGal** [comment]
Hi @armandleopold,

If your are using our bitnami/airflow chart, the easier way to install extra python modules is to mount the `requirement.txt` file as a volume as explained in our [README](https://github.com/bitnami/charts/tree/master/bitnami/airflow#install-extra-python-packages). That would install the modules on container start.

**Comment by armandleopold** [comment]
Yes and that's exactly what i am doing.
I mount a configmap to the `/bitnami/python/` **PATH** with key : `requirements.txt`

Still it doesn'y work.

**Comment by FraPazGal** [comment]
Hi @armandleopold,

Setting the parameters `extraVolumes` and `extraVolumeMounts` worked for me. Here is the install configuration I used:

Conf.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-requirements
data:
  requirements.txt: |-
    elasticsearch
    elasticsearch_dsl
```
Values.yaml:
```yaml
  worker:
    extraVolumes: |-
      - name: test-req
        configMap:
          name: test-requirements

    extraVolumeMounts: |-
      - name: test-req
        mountPath: /bitnami/python
```

```
$ kubectl logs air-airflow-worker-0

Welcome to the Bitnami airflow-worker container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow-worker
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow-worker/issues

nami    INFO  Initializing airflow-worker
airflow INFO  ==> No injected configuration files found. Creating default config file...
airflow INFO  ==> Configuring Airflow database...
airflow INFO  ==> Setting Airflow Fernet key...
airflow INFO  ==> Configuring Airflow Celery Executor...
airflow INFO  ==> Deploying Airflow from scratch...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at air-postgresql:5432
postgre INFO  PostgreSQL server listening and working at air-postgresql:5432
airflow INFO  ==> Waiting for Airflow Webserver host...
airflow INFO  ==> Waiting for Redis host...
airflow INFO
airflow INFO  ########################################################################
airflow INFO   Installation parameters for airflow-worker:
airflow INFO     Webserver URL: air-airflow:8080
airflow INFO   This installation requires no credentials.
airflow INFO  ########################################################################
airflow INFO
nami    INFO  airflow-worker successfully initialized
INFO  ==> Starting airflow-worker...
WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting elasticsearch
  Downloading elasticsearch-7.9.1-py2.py3-none-any.whl (219 kB)
Collecting elasticsearch_dsl
  Downloading elasticsearch_dsl-7.3.0-py2.py3-none-any.whl (62 kB)
Requirement already satisfied: certifi in /opt/bitnami/airflow/venv/lib/python3.6/site-packages (from elasticsearch->-r /bitnami/python/requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: urllib3>=1.21.1 in /opt/bitnami/airflow/venv/lib/python3.6/site-packages (from elasticsearch->-r /bitnami/python/requirements.txt (line 1)) (1.25.10)
Requirement already satisfied: python-dateutil in /opt/bitnami/airflow/venv/lib/python3.6/site-packages (from elasticsearch_dsl->-r /bitnami/python/requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: six in /opt/bitnami/airflow/venv/lib/python3.6/site-packages (from elasticsearch_dsl->-r /bitnami/python/requirements.txt (line 2)) (1.15.0)
Installing collected packages: elasticsearch, elasticsearch-dsl
Successfully installed elasticsearch-7.9.1 elasticsearch-dsl-7.3.0
WARNING: You are using pip version 20.2.2; however, version 20.2.4 is available.
You should consider upgrading via the '/opt/bitnami/airflow/venv/bin/python -m pip install --upgrade pip' command.
Waiting for db...
Database is ready
INFO  ==> Starting airflow...
/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=1001 euid=1001 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-11-06 11:36:39,706: INFO/MainProcess] Connected to redis://:**@air-redis-master:6379/1
[2020-11-06 11:36:39,730: INFO/MainProcess] mingle: searching for neighbors
Starting flask
 * Serving Flask app "airflow.bin.cli" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2020-11-06 11:36:40,125] {_internal.py:122} INFO -  * Running on http://0.0.0.0:8793/ (Press CTRL+C to quit)
[2020-11-06 11:36:40,761: INFO/MainProcess] mingle: all alone
[2020-11-06 11:36:40,786: INFO/MainProcess] celery@air-airflow-worker-0 ready.
```

Were these the steps you followed? If not, could you please paste them here?

**Comment by armandleopold** [comment]
I have done exactly what you have done for the Worker, but in my case for the Scheduler & the WebUI
## The Configmap :
![image](https://user-images.githubusercontent.com/7100281/98718054-35362080-238e-11eb-9a27-4b33ac5b50ba.png)

## The reference & mount :
![image](https://user-images.githubusercontent.com/7100281/98718104-4717c380-238e-11eb-9db2-8275ef97751b.png)

Still getting the error: 

```
 
 
Subscribe to project updates by watching  
Submit issues and feature requests at  
 
nami    INFO  Initializing airflow 
airflow INFO  ==> No injected configuration files found. Creating default config file... 
Error executing 'postInstallation': Unable to load the config, contains a configuration error. 
Traceback (most recent call last): 
  File "/opt/bitnami/python/lib/python3.6/logging/config.py", line 390, in resolve 
    found = getattr(found, frag) 
AttributeError: module 'airflow.utils.log' has no attribute 'es_task_handler' 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/opt/bitnami/python/lib/python3.6/logging/config.py", line 392, in resolve 
    self.importer(used) 
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/log/es_task_handler.py", line 21, in <module> 
    import elasticsearch 
ModuleNotFoundError: No module named 'elasticsearch' 
 
The above exception was the direct cause of the following exception: 
 
Traceback (most recent call last): 
  File "/opt/bitnami/python/lib/python3.6/logging/config.py", line 565, in configure 
    handler = self.configure_handler(handlers[name]) 
  File "/opt/bitnami/python/lib/python3.6/logging/config.py", line 715, in configure_handler 
    klass = self.resolve(cname) 
  File "/opt/bitnami/python/lib/python3.6/logging/config.py", line 399, in resolve 
    raise v 
  File "/opt/bitnami/python/lib/python3.6/logging/config.py", line 392, in resolve 
    self.importer(used) 
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/log/es_task_handler.py", line 21, in <module> 
    import elasticsearch 
ValueError: Cannot resolve 'airflow.utils.log.es_task_handler.ElasticsearchTaskHandler': No module named 'elasticsearch' 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/opt/bitnami/airflow/venv/bin/airflow", line 25, in <module> 
    from airflow.configuration import conf 
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/__init__.py", line 47, in <module> 
    settings.initialize() 
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/settings.py", line 402, in initialize 
    LOGGING_CLASS_PATH = configure_logging() 
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/logging_config.py", line 68, in configure_logging 
    raise e 
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/logging_config.py", line 63, in configure_logging 
    dictConfig(logging_config) 
  File "/opt/bitnami/python/lib/python3.6/logging/config.py", line 802, in dictConfig 
    dictConfigClass(config).configure() 
  File "/opt/bitnami/python/lib/python3.6/logging/config.py", line 573, in configure 
    '%r: %s' % (name, e)) 
ValueError: Unable to configure handler 'task': Cannot resolve 'airflow.utils.log.es_task_handler.ElasticsearchTaskHandler': No module named 'elasticsearch' 
 
```

**Comment by FraPazGal** [comment]
Hi @armandleopold,

Using the same configMap and adding the same values used in my example to `web/scheduler.extraVolumes` and `web/scheduler.extraVolumesMounts` in `values.yaml` file should install the modules. From your logs, your pod fails just after starting the initialising airflow, but the modules installation should occur at the latest steps. Are you changing anything besides the volumes-related parameters from `values.yaml`? If so, could you share your custom `values.yaml`?

**Comment by armandleopold** [comment]
In your exemple your are using the CeleryExecutor, but i am using the KubernetesExecutor

I have added some extraEnvVars : 

```
airflow:
...
  extraEnvVars:
    ## Proxy
    - name: FORWARDED_ALLOW_IPS
      value: "*"
    - name: NO_PROXY
    - name: no_proxy
    - name: HTTPS_PROXY
    - name: https_proxy
    - name: HTTP_PROXY
    - name: http_proxy

    ## logging
    ## Elasticsearch
    - name: AIRFLOW__CORE__REMOTE_LOGGING
      value: "True"
    - name: AIRFLOW__ELASTICSEARCH__FRONTEND
      value: "airflow-deployement-kibana:5601"
    - name: AIRFLOW__ELASTICSEARCH__HOST
      value: "elasticsearch-master:9200"
    - name: AIRFLOW__ELASTICSEARCH__WRITE_STDOUT
      value: "True"
    - name: AIRFLOW__ELASTICSEARCH__JSON_FORMAT
      value: "True"
    ## Webserver
    - name: AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW
      value: "graph"
    ## LDAP 
    - name: AIRFLOW__LDAP__CACERT
      value: "/opt/bitnami/airflow/conf/certs/ca.pem"
    ## kubernetesExecutor
    - name: AIRFLOW_EXECUTOR
      value: "KubernetesExecutor"
    - name: AIRFLOW__KUBERNETES__FS_GROUP
      value: "50000"
    - name: AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME
      value: "airflow-deployement"
    - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY
      value: "bitnami/airflow-worker"
    - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG
      value: "1.10.12-debian-10-r47"
    ## Git DAGS
    - name: AIRFLOW__KUBERNETES__GIT_REPO
      value: "https://........................git"
    - name: AIRFLOW__KUBERNETES__GIT_BRANCH
      value: ""
    - name: AIRFLOW__KUBERNETES__GIT_USER
      value: ""
    - name: AIRFLOW__KUBERNETES__GIT_PASSWORD
      value: ""
    - name: AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT
      value: "/opt/bitnami/airflow/dags/git-airflow-dags"
    - name: AIRFLOW__KUBERNETES__GIT_SYNC_ROOT
      value: "/dags-airflow-dags"
    - name: AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH
      value: "./repo/"
    ## SMTP
    - name: AIRFLOW__SMTP__SMTP_HOST
      value: "smtpint.curie.net"
    - name: AIRFLOW__SMTP__SMTP_STARTTLS
      value: "False"
    - name: AIRFLOW__SMTP__SMTP_MAIL_FROM
      value: "postmaster@dev-airflow-data.curie.net"
```
