### ISSUE TITLE
Upgrade for Airflow 2.0.0

### ISSUE THREAD

**Issue by armandleopold** [bitnami/bitnami-docker-airflow#63]
Is there plan to upgrade the chart to Airflow 2.0 ? Especially for the Kubernetes Executor/Operator  ?
Link : [Airflow 2.0.0](https://github.com/apache/airflow/releases/tag/2.0.0)

**Comment by beltran-rubo** [comment]
thanks @armandleopold! We just started working on it. As it is a major version it could take some time to be released, we will keep you in the loop.

**Comment by VORUSRIK000** [comment]
We are looking for the same, especially to get the updated Azure Integrations (AzureSQL thru ODBC, KeyVault). Would like to get tagged (if anything like that) when the version is released.

**Comment by armandleopold** [comment]
> thanks @armandleopold! We just started working on it. As it is a major version it could take some time to be released, we will keep you in the loop.

Alright Good luck, really looking forward to use it at our Institut Curie's Data Factory ;-)

**Comment by carrodher** [comment]
Thanks for the interest, we are actively working on it. As it is a major version there are some manual steps required on our side to adapt our internal test & release pipeline, when everything is ready a new folder will appear in this repository and new tags (`2`, `2-debian-10`, `2.0.0`, etc) will be pushed to the different registries. We will update this thread once released.

**Comment by iercan** [comment]
@carrodher I saw 2.0.0 is released but when I install it I'm not able to use UI. It looks like this and butttons not work. 
![image](https://user-images.githubusercontent.com/3406152/105002126-dbaf3980-5a41-11eb-92ff-cd2eca508f83.png)

**Comment by andresbono** [comment]
Hi @iercan, thanks for reporting the issue.

- How are you installing Airflow 2.0.0?
- What is the URL that you are accessing to?
- Can you open your web browser console and see if there are any errors?

**Comment by iercan** [comment]
I used below docker compose file which is same one I use with version 1.10.14. 
I tried both upgrade and clean install, result is same. 
```
version: '2.4'
services:
  postgresql:
    image: postgres:9.6
    restart: on-failure
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  redis:
    restart: on-failure
    image: 'redis:5.0.5'
 
  airflow:
    image: bitnami/airflow:2.0.0
    restart: on-failure
    depends_on:
      - postgresql
      - redis
    env_file:
      - airflow.env
    ports:
      - '8080:8080'
    volumes:
      - ./logs:/opt/bitnami/airflow/logs
      - ./dags:/opt/bitnami/airflow/dags
  
  scheduler:
    image: bitnami/airflow-scheduler:2.0.0
    restart: on-failure
    depends_on:
      - postgresql
      - redis
    env_file:
      - airflow.env
    volumes:
      - ./logs:/opt/bitnami/airflow/logs
      - ./dags:/opt/bitnami/airflow/dags

  worker:
    image: bitnami/airflow-worker:2.0.0
    restart: on-failure
    depends_on:
      - postgresql
      - redis
    env_file:
      - airflow.env
    volumes:
      - ./logs:/opt/bitnami/airflow/logs
      - ./dags:/opt/bitnami/airflow/dags
```

I'm connecting as http://localhost:8080
I check browser console. Looks like api can not reach /static url
![image](https://user-images.githubusercontent.com/3406152/105031090-d82da980-5a65-11eb-90ae-82468fe1cc4c.png)
