### ISSUE TITLE
airflow 2 cannot provide some static files

### ISSUE THREAD

**Issue by WqyJh** [bitnami/bitnami-docker-airflow#65]
`docker.io/bitnami/airflow:2-debian-10` do not provide some static files. As is shown in the picture, the url of some css files are `/static/` which is wrong. However, `docker.io/bitnami/airflow:1-debian-10` works fine.

![image](https://user-images.githubusercontent.com/15232241/105028919-a1b75500-5a8c-11eb-91f5-c36adec5e8d2.png)

There're only some static files are supported as shown in the following picture which is the contents inside a running airflow 2 container.

![image](https://user-images.githubusercontent.com/15232241/105029287-1d190680-5a8d-11eb-8cde-e5791484d46b.png)

There're much more files inside an airflow 1 container.

![image](https://user-images.githubusercontent.com/15232241/105029720-acbeb500-5a8d-11eb-8392-6af7464cb345.png)

**Steps to reproduce the issue:**

1. [First Step]
This is the content of `docker-compose.yml`, then use `docker-compose up -d` to start the services. The image digest is `2e1e89b5b095`.

```yaml
version: '2'

services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:10-debian-10'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    volumes:
      - 'redis_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2.0.0-debian-10-r1
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    volumes:
      - airflow_scheduler_data:/bitnami
  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2-debian-10
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    volumes:
      - airflow_worker_data:/bitnami
  airflow:
    image: docker.io/bitnami/airflow:2-debian-10
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami
volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
```
2. [Second Step]
Go to the http://127.0.0.1:8080 and login.
