### ISSUE TITLE
LDAP not work as expected

### ISSUE THREAD

**Issue by WqyJh** [bitnami/bitnami-docker-airflow#66]
**Description**

I use [docker-compose-ldap.yaml](https://github.com/bitnami/bitnami-docker-airflow/blob/master/docker-compose-ldap.yml) to test LDAP support.

As the following config shows, there're two accounts `customuser/custompassword` and `user2/password2`. I could login with the former but couldn't login with the latter one. This is because the flask-appbuilder need to set `AUTH_USER_REGISTRATION=True` to create an User Record in the database.

So please add two configuration environment variable for `AUTH_USER_REGISTRATION` and `AUTH_USER_REGISTRATION_ROLE`.

```yaml
  airflow:
    image: docker.io/bitnami/airflow:2-debian-10
    environment:
      - AIRFLOW_LDAP_ENABLE=yes
      - AIRFLOW_LDAP_URI=ldap://openldap:1389
      - AIRFLOW_LDAP_SEARCH=dc=example,dc=org
      - AIRFLOW_LDAP_BIND_USER=cn=admin,dc=example,dc=org
      - AIRFLOW_LDAP_BIND_PASSWORD=adminpassword
      - AIRFLOW_LDAP_UID_FIELD=uid
      - AIRFLOW_LDAP_USE_TLS=False
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=customuser
      - AIRFLOW_EMAIL=user@example.com
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami
  openldap:
    image: 'docker.io/bitnami/openldap:latest'
    ports:
      - '1389:1389'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=customuser,user2
      - LDAP_PASSWORDS=custompassword,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'
```
