### ISSUE TITLE
LDAP External Server

### ISSUE THREAD

**Issue by danielccruz** [bitnami/bitnami-docker-airflow#69]
**Description**

I was trying to integrate your docker-compose with my own LDAP server but I couldn't get it working. I did a few tests with the LDAP_URI and I could see a "Resource Unavailable" when I passed the wrong URI.  When the correct URI is passed I get the error below. It seems to me that it is something to do with a TLS configuration.

The relevant configurations are the ones below.
```yaml
 airflow:
    image: bitnami/airflow:latest
    environment:
      - ...
      - AIRFLOW_LDAP_ENABLE=yes
      - AIRFLOW_LDAP_URI=ldaps://HOST:PORT
      - AIRFLOW_LDAP_SEARCH=cn=groups,cn=accounts,dc=***,dc=***,dc=***,dc=***
      - AIRFLOW_LDAP_BIND_USER=uid=***,cn=users,cn=accounts,dc=***,dc=***,dc=***,dc=***
      - AIRFLOW_LDAP_BIND_PASSWORD=***
      - AIRFLOW_LDAP_UID_FIELD=uid
      - AIRFLOW_LDAP_USE_TLS=True
      - AIRFLOW_LDAP_TLS_CA_CERTIFICATE=/.../cacert.pem
      - ...
```

```
[2021-02-10 18:42:34,579] {app.py:1891} ERROR - Exception on /login/ [POST]
airflow_1            | Traceback (most recent call last):
airflow_1            |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
airflow_1            |     response = self.full_dispatch_request()
airflow_1            |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
airflow_1            |     rv = self.handle_user_exception(e)
airflow_1            |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
airflow_1            |     reraise(exc_type, exc_value, tb)
airflow_1            |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
airflow_1            |     raise value
airflow_1            |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
airflow_1            |     rv = self.dispatch_request()
airflow_1            |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
airflow_1            |     return self.view_functions[rule.endpoint](**req.view_args)
airflow_1            |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/flask_appbuilder/security/views.py", line 514, in login
airflow_1            |     user = self.appbuilder.sm.auth_user_ldap(
airflow_1            |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/flask_appbuilder/security/manager.py", line 897, in auth_user_ldap
airflow_1            |     ldap.set_option(ldap.OPT_X_TLS_NEWCTX, 0)
airflow_1            |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/ldap/functions.py", line 115, in set_option
airflow_1            |     return _ldap_function_call(None,_ldap.set_option,option,invalue)
airflow_1            |   File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/ldap/functions.py", line 55, in _ldap_function_call
airflow_1            |     result = func(*args,**kwargs)
airflow_1            | ValueError: option error
```

From your issues, it seems to me that people always use your LDAP container instead of an external server. So my question is, does it work with an external LDAP server or I will have to deploy another container with it?

Best regards
