### ISSUE TITLE
Cannot add custom DAG

### ISSUE THREAD

**Issue by gfelot** [bitnami/bitnami-docker-airflow#76]
**Description**

Following the instructions I tried to add custom DAGs
https://github.com/bitnami/bitnami-docker-airflow#load-dag-files

here the airflow config
```
    airflow:
        image: bitnami/airflow:latest
        environment:
            - AIRFLOW_DATABASE_NAME=bitnami_airflow
            - AIRFLOW_DATABASE_USERNAME=bn_airflow
            - AIRFLOW_DATABASE_PASSWORD=bitnami1
            - AIRFLOW_EXECUTOR=CeleryExecutor
        ports:
            - '8080:8080'
        volumes:
            - airflow_data:/bitnami
            - requirement:/bitnami/python
            - dags:/opt/bitnami/airflow/dags
```
**Describe the results you received:**

I cannot find my custom dag (to be sure I took the PythonOperator exemple and renamed it)
